### ISSUE TITLE
ExpandDirectory and CacheDirectory need to move elsewhere in config

### ISSUE THREAD

**Issue by dmjacobsen** [NERSC/shifter#40] opened 2016-05-07 03:38 UTC
need to have finer grain configuration for imageworker cache and expand directories;  if we ever get to the state where imageworkers are more distributed, the same path may not be workable across all systems.

need to consider cases of workers consolidated onto a single node for multiple nodes pulling same image concurrently.

need to consider cases of workers spread out to multiple systems pulling same image frequently.  there may be value in centralizing the cache for some sites; not for others.

**Comment by scanon** [comment] 2018-03-25 17:52
This isn't an issue because the worker can have a different settings in the global section.  In addition, we are moving to a model where each system would have its own gateway.  I'm going to close this out as not a bug.

**Closed** 2018-03-25 17:53 UTC
